apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: microservice
  labels:
    project: beheroes
    department: development
    component: microservice
    app: microservice-service
spec:
  ports:
  - name: external
    port: 80
    targetPort: web
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: microservice-api
